[project]
name = "knn-with-mnist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andriana", email = "andrianasma@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
knn-with-mnist = "knn_with_mnist:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
